openapi: 3.0.0
info:
  title: Service
  description: OK!
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    Teacher:
      type: object
      properties:
        id:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        degree:
          type: string
    Abiturient:
      properties:
        id:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        numCertificate:
          type: number
    Exam:
      required:
        - subject
      properties:
        id:
          type: string
        subject:
          type: string
        date:
          type: string
        abiturientId:
          type: string
        teacherId:
          type: string
